<?php
/**
 * @var $block \Checkout\CustomizeProcess\Block\Adminhtml\Order\View\Tab\Surveytab
 */
list($income, $hobby) = $block->getCustomerSurvey();
?>

<div class="fieldset-wrapper order-information">
    <div class="fieldset-wrapper-title">
       <span class="title"><?php /* @escapeNotVerified */
           echo __('Customer Survey') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php echo $block->getChildHtml(); ?>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Hobby :') ?></th>
            <td><?=$hobby?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Income Range :') ?></th>
            <td><?=$income . ' (per week)'?></td>
        </tr>
        </tbody>
    </table>
</div>
